In [1]:
import pandas as pd

In [2]:
chat = pd.read_csv('E:\Python Program\Codeacademy_projects\Twitch\chat.csv', names = ['Time', 'Device_id', 'Login', 'Channel', 'Country', 'Player', 'Game'])
stream = pd.read_csv('E:\Python Program\Codeacademy_projects\Twitch\stream.csv')

                   Start by getting a feel for the stream table and the chat table:

1. Select all columns from the first 20 rows.

   What columns do the tables have?

In [3]:
stream.head(20)

,time,device_id,login,channel,country,player,game,stream_format,subscriber
0,01/01/2015 18:33,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN
1,01/01/2015 23:35,9a8cc2b7162b99c0a0f501dc9a5ec4f68586a760,5ad49a7b408ce452140b180dd6efb57a9f4d22c7,george,US,site,DayZ,chunked,False
2,01/01/2015 04:39,2f9c3f9ee1033b71a3819564243f20ef3bec0183,5b9a43e68f019185f55615d0b83019dee4b5d06f,frank,US,site,League of Legends,chunked,False
3,01/01/2015 11:15,0cda8226ba2583424c80c3c1c22c1256b080ad17,02c7797faa4d8a3ff4b0c14ee1764b6817b53d0b,estelle,CH,site,Dota 2,high,False
4,01/01/2015 11:28,e3288ca5e3153aa85e32f64cdd994b7666968dcf,b920c228acbcbebee26d9c79f6eb73b73a9480c7,morty,FR,site,Heroes of the Storm,medium,False
5,01/01/2015 23:27,343fe2bfd58595d5c18602d420ecf6f9d694d5a8,7814f661a54349ff5eee84f9d6f476918c9b7270,george,US,iphone_t,DayZ,NaN,NaN
6,01/01/2015 21:09,80a0c7d1abb6a5a0060e18202b77bef831e08ca5,eb158cab3f606d3894a32e20bddbfd2d589095a9,frank,US,site,League of Legends,high,True
7,01/01/2015 19:14,1e342e5e4e228f617449029054b3bb19c5224528,2aaf6a414bc3dc923b04f986de7ba1b8101c6698,frank,CA,site,League of Legends,high,False
8,01/01/2015 13:51,272cffbb1a9a33ad3bb48a2ee9ae5cbcac5ca22e,401716920e3435b5e3eec9fc4ccd6a44c7af38f5,kramer,TR,site,Counter-Strike: Global Offensive,chunked,False
9,01/01/2015 22:00,593ed161c456eeeb9e18b8005786d42abc1a7373,ef24dc49ceb4bcd3cccb0fa862d8a150ecf935e1,frank,US,site,League of Legends,medium,False
10,01/01/2015 19:10,16679ceba8bf5fb10f253e51f9a286c11b011e02,3b8deb77fb36b6147c27cbdb82a925aaf26b629b,jerry,RU,embed,Dota 2,chunked,False
11,01/01/2015 22:59,1a247324beabdb85b2b8a97472f28f6cf9026fe1,c485d2914068876ebd6cf3ee6812dc939abae8d7,frank,US,android,League of Legends,NaN,NaN
12,01/01/2015 22:10,20bde4b4418df3ce2701869233e12b1b4a30da88,7abc32d6617b4a13b78dd2710f22fe8a2305f0fd,george,US,ipad_t,DayZ,NaN,NaN
13,01/01/2015 13:46,21d94696c9b0f4f9eafc785a2d9d1be1982244b1,c2de0a4d1258e2fc093017d5a793a625af9a0d44,estelle,US,embed,Dota 2,high,False
14,01/01/2015 10:07,5e3a498f6c671a42edfa3772c87c1c3dc918a511,ffec857d76dcf8cfee7f3a96028365f33964c823,morty,NaN,ipad_t,Heroes of the Storm,NaN,NaN
15,01/01/2015 21:04,2e7bcee08428c8ba8c5ce7d44a930dfee7f34db2,4fac13dc5b1cc9d3b18ad0ff62da2adb635375fd,frank,US,site,League of Legends,high,False
16,01/01/2015 12:41,88b8d83a7ac64d30f2b3f54cc9d9c2a15bb2f666,9f2d3dcb56169dcdc0933d21004ce0f2e40b0df0,estelle,TR,site,Dota 2,high,False
17,01/01/2015 21:30,53fc815c5fb6e8641dc8a60cf2cc480198a2ba17,122ab65809db2c8057c998d0664b2f54f5f6aa10,frank,US,android,League of Legends,NaN,NaN
18,01/01/2015 22:03,f74aae10baab29ab434519adb4ad4f64f6d90727,3b954baa601d4cb22610dc4727543c697acbd4d6,frank,US,iphone_t,League of Legends,NaN,NaN
19,01/01/2015 14:47,47d380927c426e589be566d4ae967cbb6f9d2d13,40b89a7097d30ecf1fe4591442f541ed500c5b8b,helen,CA,iphone_t,Hearthstone: Heroes of Warcraft,NaN,NaN

2. What are the unique games in the stream table?

In [4]:
stream['game'].unique()

array(['League of Legends', 'DayZ', 'Dota 2', 'Heroes of the Storm',
       'Counter-Strike: Global Offensive',
       'Hearthstone: Heroes of Warcraft', 'The Binding of Isaac: Rebirth',
       'Agar.io', 'Gaming Talk Shows', nan, 'Rocket League',
       'World of Tanks', 'ARK: Survival Evolved', 'SpeedRunners',
       'Breaking Point', 'Duck Game', 'Devil May Cry 4: Special Edition',
       'Block N Load', 'Fallout 3', 'Batman: Arkham Knight',
       'Reign Of Kings', 'The Witcher 3: Wild Hunt',
       'The Elder Scrolls V: Skyrim', 'Super Mario Bros.', 'H1Z1',
       'The Last of Us', 'Depth', 'Mortal Kombat X',
       'Senran Kagura: Estival Versus', 'The Sims 4',
       'You Must Build A Boat', 'Choice Chamber', 'Music', 'Risk of Rain',
       'Grand Theft Auto V', 'Besiege', 'Super Mario Bros. 3', 'Hektor',
       'Bridge Constructor Medieval', 'Lucius', 'Blackjack',
       'Cities: Skylines'], dtype=object)

3. What are the unique channels in the stream table?

In [5]:
stream['channel'].unique()

array(['frank', 'george', 'estelle', 'morty', 'kramer', 'jerry', 'helen',
       'newman', 'elaine', 'susan'], dtype=object)

4. What are the most popular games in the stream table?

    Create a list of games and their number of viewers using GROUP BY.

In [6]:
stream['game'].value_counts()

League of Legends                   193533
Dota 2                               85608
Counter-Strike: Global Offensive     54438
DayZ                                 38004
Heroes of the Storm                  35310
The Binding of Isaac: Rebirth        29467
Gaming Talk Shows                    28115
World of Tanks                       15932
Hearthstone: Heroes of Warcraft      14399
Agar.io                              11480
Rocket League                         7087
ARK: Survival Evolved                 4158
SpeedRunners                          3367
Duck Game                             1063
Fallout 3                              485
Devil May Cry 4: Special Edition       231
Breaking Point                         161
Batman: Arkham Knight                  117
Reign Of Kings                          50
The Witcher 3: Wild Hunt                45
Block N Load                            34
Depth                                   27
Mortal Kombat X                         22
H1Z1                                     7
Super Mario Bros.                        6
Grand Theft Auto V                       5
Music                                    4
The Last of Us                           3
The Elder Scrolls V: Skyrim              3
Senran Kagura: Estival Versus            2
Risk of Rain                             2
Bridge Constructor Medieval              1
The Sims 4                               1
Cities: Skylines                         1
Besiege                                  1
Lucius                                   1
Blackjack                                1
Hektor                                   1
You Must Build A Boat                    1
Choice Chamber                           1
Super Mario Bros. 3                      1
Name: game, dtype: int64

5.  These are some big numbers from the game League of Legends (also known as LoL).

    Where are these LoL stream viewers located?

    Create a list of countries and their number of LoL

In [7]:
filt = stream['game']=='League of Legends'

In [8]:
stream.loc[filt]['country'].value_counts()

US    85606
CA    13034
DE    10835
GB     6964
TR     4412
      ...
SC        1
A1        1
MQ        1
AZ        1
GY        1
Name: country, Length: 155, dtype: int64


6. The player column contains the source the user is using to view the stream (site, iphone, android, etc).

    Create a list of players and their number of streamers.

In [9]:
stream['player'].value_counts()

site             246115
iphone_t         100689
android           93508
ipad_t            53646
embed             19819
xbox_one           4863
home               3479
frontpage          1567
amazon             1155
xbox360             985
roku                233
chromecast          149
facebook             83
nvidia shield         3
ouya                  3
android_pip           2
Name: player, dtype: int64

7. Create a new column named genre for each of the games.

    Group the games into their genres: Multiplayer Online Battle Arena (MOBA), First Person Shooter (FPS), Survival, and Other.

    Using CASE, your logic should be:

    If League of Legends → MOBA
    If Dota 2 → MOBA
    If Heroes of the Strom → MOBA
    If Counter-Strike: Global Offensive → FPS
    If DayZ → Survival
    If Survival Evolved → Survival
    Else → Other

In [10]:
# country_group = stream.groupby(['country'])
# country_group['game'].value_counts().loc['US']

In [11]:
def fnc (string):
    if string == 'League of Legends':
        return 'MOBA'
    elif string == 'Dota 2':
        return 'MOBA'
    elif string == 'Heroes of the Storm':
        return 'MOBA'
    elif string == 'Counter-Strike: Global Offensive':
        return 'FPS'
    elif string == 'DayZ':
        return 'Survival'
    elif string == 'ARK: Survival Evolved':
        return 'Survival'
    else:
        return 'Other'

In [12]:
# game_group = stream.groupby(['game'])
# game_group.get_group('League of Legends')[['country', 'game']]

In [13]:
stream['genre'] = stream['game'].apply(fnc)

In [14]:
stream.groupby(['game', 'genre'])['game'].count().reset_index(name='count').sort_values('count', ascending=False)

                                game     genre   count
23                 League of Legends      MOBA  193533
14                            Dota 2      MOBA   85608
10  Counter-Strike: Global Offensive       FPS   54438
11                              DayZ  Survival   38004
22               Heroes of the Storm      MOBA   35310
34     The Binding of Isaac: Rebirth     Other   29467
17                 Gaming Talk Shows     Other   28115
39                    World of Tanks     Other   15932
20   Hearthstone: Heroes of Warcraft     Other   14399
1                            Agar.io     Other   11480
29                     Rocket League     Other    7087
0              ARK: Survival Evolved  Survival    4158
31                      SpeedRunners     Other    3367
15                         Duck Game     Other    1063
16                         Fallout 3     Other     485
13  Devil May Cry 4: Special Edition     Other     231
6                     Breaking Point     Other     161
2              Batman: Arkham Knight     Other     117
27                    Reign Of Kings     Other      50
38          The Witcher 3: Wild Hunt     Other      45
5                       Block N Load     Other      34
12                             Depth     Other      27
25                   Mortal Kombat X     Other      22
19                              H1Z1     Other       7
32                 Super Mario Bros.     Other       6
18                Grand Theft Auto V     Other       5
26                             Music     Other       4
35       The Elder Scrolls V: Skyrim     Other       3
36                    The Last of Us     Other       3
28                      Risk of Rain     Other       2
30     Senran Kagura: Estival Versus     Other       2
24                            Lucius     Other       1
4                          Blackjack     Other       1
21                            Hektor     Other       1
7        Bridge Constructor Medieval     Other       1
33               Super Mario Bros. 3     Other       1
3                            Besiege     Other       1
37                        The Sims 4     Other       1
8                     Choice Chamber     Other       1
9                   Cities: Skylines     Other       1
40             You Must Build A Boat     Other       1

8. Let’s write a query that returns three columns:

    The hours of the time column
    The view count for each hour
    Lastly, filter the result with only the users in your country

In [15]:
stream['time'] =  pd.to_datetime(stream['time'])

In [16]:
stream['time'].head()

0   2015-01-01 18:33:00
1   2015-01-01 23:35:00
2   2015-01-01 04:39:00
3   2015-01-01 11:15:00
4   2015-01-01 11:28:00
Name: time, dtype: datetime64[ns]

In [17]:
stream['Hour_of_the_day'] = stream['time'].dt.hour
stream.head()

,time,device_id,login,channel,country,player,game,stream_format,subscriber,genre,Hour_of_the_day
0,2015-01-01 18:33:00,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,18
1,2015-01-01 23:35:00,9a8cc2b7162b99c0a0f501dc9a5ec4f68586a760,5ad49a7b408ce452140b180dd6efb57a9f4d22c7,george,US,site,DayZ,chunked,False,Survival,23
2,2015-01-01 04:39:00,2f9c3f9ee1033b71a3819564243f20ef3bec0183,5b9a43e68f019185f55615d0b83019dee4b5d06f,frank,US,site,League of Legends,chunked,False,MOBA,4
3,2015-01-01 11:15:00,0cda8226ba2583424c80c3c1c22c1256b080ad17,02c7797faa4d8a3ff4b0c14ee1764b6817b53d0b,estelle,CH,site,Dota 2,high,False,MOBA,11
4,2015-01-01 11:28:00,e3288ca5e3153aa85e32f64cdd994b7666968dcf,b920c228acbcbebee26d9c79f6eb73b73a9480c7,morty,FR,site,Heroes of the Storm,medium,False,MOBA,11

In [18]:
filt = stream['country']=='US'
stream.loc[filt].groupby(['Hour_of_the_day'])['Hour_of_the_day'].count().reset_index(name='count').sort_values(by='Hour_of_the_day', ascending=True)

    Hour_of_the_day  count
0                 0   7025
1                 1   4693
2                 2   5961
3                 3   4236
4                 4   3567
5                 5   1597
6                 6    236
7                 7    338
8                 8    935
9                 9   1214
10               10   1940
11               11   7349
12               12  11766
13               13   9740
14               14   7521
15               15   9065
16               16  10134
17               17  11929
18               18  12215
19               19  15206
20               20  19656
21               21  18425
22               22  13984
23               23  11646

9.  The stream table and the chat table share a column: device_id.

    Let’s join the two tables on that column

In [22]:
stream_chat = pd.merge(stream, chat, left_on='device_id', right_on='Device_id', how='inner')

In [23]:
stream_chat.head()

,time,device_id,login,channel,country,player,game,stream_format,subscriber,genre,Hour_of_the_day,Time,Device_id,Login,Channel,Country,Player,Game
0,2015-01-01 18:33:00,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,18,01/01/2015 22:43,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
1,2015-01-01 23:11:00,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,23,01/01/2015 22:43,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
2,2015-01-01 17:29:00,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,17,01/01/2015 22:43,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
3,2015-01-01 16:39:00,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,16,01/01/2015 22:43,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends
4,2015-01-01 21:54:00,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends,NaN,NaN,MOBA,21,01/01/2015 22:43,40ffc2fa6534cf760becbdbf5311e31ad069e46e,085c1eb7b587bfe654f0df7b4ba7f4fc4013636c,frank,US,iphone_t,League of Legends